export const ticketFactoryAbi = [
  {
    type: "function",
    name: "createEvent",
    inputs: [
      { name: "_name", type: "string" },
      { name: "_venue", type: "string" },
      { name: "_date", type: "uint256" },
      { name: "_price", type: "uint256" },
      { name: "_maxSupply", type: "uint256" },
      { name: "_transferable", type: "bool" },
    ],
    outputs: [{ name: "eventAddress", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getEvents",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEventCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "events",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "implementation",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creationFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "EventCreated",
    inputs: [
      { name: "eventAddress", type: "address", indexed: true },
      { name: "organizer", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "date", type: "uint256", indexed: false },
      { name: "price", type: "uint256", indexed: false },
      { name: "maxSupply", type: "uint256", indexed: false },
    ],
  },
] as const;
